<?php

declare(strict_types=1);

namespace TypeLang\Mapper\Tests\Mapping\Metadata;

use PHPUnit\Framework\Attributes\CoversClass;
use TypeLang\Mapper\Mapping\Metadata\Metadata;

#[CoversClass(Metadata::class)]
final class MetadataTest extends MetadataTestCase
{
    public function testTimestampIsFromConstructor(): void
    {
        $m = new class (123) extends Metadata {};

        self::assertSame(123, $m->getTimestamp());
    }

    public function testTimestampAutoGeneratedIsInt(): void
    {
        $m = new class () extends Metadata {};

        self::assertIsInt($m->getTimestamp());
        self::assertGreaterThanOrEqual(0, $m->getTimestamp());
    }
}


