<?php

exit(1);

/**
 * List of supported annotations for IDE autocomplete
 *
 * @var
 * @phan-var
 * @psalm-var
 * @phpstan-var
 * @property
 * @phpstan-property
 * @property-read
 * @phpstan-property-read
 * @property-write
 * @phpstan-property-write
 * @method
 * @phan-method
 * @psalm-method
 * @phpstan-method
 * @extends
 * @phan-extends
 * @phan-inherits
 * @template-extends
 * @phpstan-extends
 * @implements
 * @template-implements
 * @phpstan-implements
 * @use
 * @template-use
 * @phpstan-use
 * @template
 * @phan-template
 * @psalm-template
 * @phpstan-template
 * @template-covariant
 * @psalm-template-covariant
 * @phpstan-template-covariant
 * @template-contravariant
 * @psalm-template-contravariant
 * @phpstan-template-contravariant
 * @param
 * @phan-param
 * @psalm-param
 * @phpstan-param
 * @param-out
 * @psalm-param-out
 * @phpstan-param-out
 * @param-immediately-invoked-callable
 * @phpstan-param-immediately-invoked-callable
 * @param-later-invoked-callable
 * @phpstan-param-later-invoked-callable
 * @param-closure-this
 * @phpstan-param-closure-this
 * @return
 * @phan-return
 * @phan-real-return
 * @psalm-return
 * @phpstan-return
 * @phpstan-throws
 * @throws
 * @psalm-require-extends
 * @phpstan-require-extends
 * @psalm-require-implements
 * @phpstan-require-implements
 * @psalm-inheritors
 * @phpstan-sealed
 * @phan-type
 * @psalm-type
 * @phpstan-type
 * @psalm-import-type
 * @phpstan-import-type
 * @phpstan-assert
 * @psalm-assert
 * @phan-assert
 * @phpstan-assert-if-true
 * @psalm-assert-if-true
 * @phan-assert-if-true
 * @phpstan-assert-if-false
 * @psalm-assert-if-false
 * @phan-assert-if-false
 * @phpstan-this-out
 * @phpstan-self-out
 * @psalm-this-out
 * @psalm-self-out
 * @deprecated
 * @not-deprecated
 * @internal
 * @final
 * @pure
 * @phan-pure
 * @phan-side-effect-free
 * @psalm-pure
 * @phpstan-pure
 * @impure
 * @phpstan-impure
 * @readonly
 * @phan-read-only
 * @psalm-readonly
 * @phpstan-readonly
 * @phpstan-readonly-allow-private-mutation
 * @psalm-readonly-allow-private-mutation
 * @immutable
 * @phan-immutable
 * @psalm-immutable
 * @phpstan-immutable
 * @consistent-constructor
 * @phpstan-consistent-constructor
 * @psalm-consistent-constructor
 * @no-named-arguments
 * @phpstan-allow-private-mutation
 * @psalm-allow-private-mutation
 */
function PS_UNRESERVE_PREFIX__(): void {}
