name: bench

on:
  push:
  pull_request:

jobs:
  bench:
    name: Benchmarks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.4' ]
        os: [ ubuntu-latest ]
    steps:
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            cd bench
            composer update --prefer-dist --no-interaction --no-progress
      - name: Normalization Benchmarks
        continue-on-error: true
        run: |
          cd bench
          composer bench:normalize
      - name: Denormalization Benchmarks
        continue-on-error: true
        run: |
          cd bench
          composer bench:normalize
      - name: Instantiation Benchmarks
        continue-on-error: true
        run: |
          cd bench
          composer bench:instantiate
      - name: Type Extraction Benchmarks
        continue-on-error: true
        run: |
          cd bench
          composer bench:extract
